apiVersion: v1
kind: ConfigMap
metadata:
  name: nimantran-config
  namespace: nimantran
data:
  APP_ENV: "production"
  PORT: "8000"
  CORS_ORIGINS: "*"
  POSTGRES_DB: "nimantran_db"
  POSTGRES_HOST: "nimantran-postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "nimantran-redis"
  REDIS_PORT: "6379"
