apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nimantran-ingress
  namespace: nimantran
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nimantran-backend
                port:
                  number: 8000
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: nimantran-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nimantran-frontend
                port:
                  number: 80
