apiVersion: v1
kind: Secret
metadata:
  name: nimantran-secrets
  namespace: nimantran
type: Opaque
stringData:
  POSTGRES_USER: "nimantran"
  POSTGRES_PASSWORD: "nimantran_secure_password_2026"
  DATABASE_URL: "postgresql+asyncpg://nimantran:nimantran_secure_password_2026@nimantran-postgres:5432/nimantran_db"
  REDIS_URL: "redis://nimantran-redis:6379/0"
  JWT_SECRET_KEY: "nimantran_jwt_super_secret_production_key_2026"
