"""
Nimantran AI — Backend Theme Catalog Service
Provides structured celebration themes with celebration filtering,
modes (light, dark, luxury-dark, pastel, vibrant), styles, and recommended defaults.
"""
from typing import List, Dict, Any, Optional

MASTER_BACKEND_THEMES: List[Dict[str, Any]] = [
    {
        "id": "wedding-royal-heritage",
        "celebration_type": "WEDDING",
        "name": "01 — Royal Heritage",
        "tagline": "Light Ivory Paper, Rich Antique Gold & Burgundy Flora",
        "description": "Flagship wedding stationery with Indian palace arches, embossed golden filigree, realistic layered paper depth, and majestic burgundy floral accents.",
        "preview_image": "/romantic_3d_wedding_stage.jpg",
        "mode": "light",
        "style": "Royal",
        "mood": "Romantic",
        "typography": "font-serif",
        "background_style": "ivory-palace-radial",
        "decoration_style": "ROYAL_MANDAP_GARLANDS",
        "animation_style": "traditional",
        "tags": ["ROYAL", "LIGHT", "TRADITIONAL", "RECOMMENDED"],
        "recommended_occasions": ["WEDDING", "VIVAH", "MARRIAGE", "GRAND_WEDDING"],
        "is_recommended": True,
    },
    {
        "id": "wedding-midnight-royal",
        "celebration_type": "WEDDING",
        "name": "02 — Midnight Royal",
        "tagline": "Deep Burgundy Velvet & Metallic Gold Foil",
        "description": "Dramatic dark luxury wedding invitation with velvet midnight background, metallic champagne gold floral frames, and cinematic candlelight.",
        "preview_image": "/romantic_3d_invitation_hero.jpg",
        "mode": "luxury-dark",
        "style": "Luxury",
        "mood": "Glamorous",
        "typography": "font-serif",
        "background_style": "romantic-wine-radial",
        "decoration_style": "ROSE_PETALS_HEARTS",
        "animation_style": "romantic",
        "tags": ["DARK", "LUXURY", "ROMANTIC"],
        "recommended_occasions": ["WEDDING", "VIVAH", "RECEPTION"],
        "is_recommended": False,
    },
    {
        "id": "wedding-emerald-palace",
        "celebration_type": "WEDDING",
        "name": "03 — Emerald Palace",
        "tagline": "Imperial Forest Green & Royal Gold Filigree",
        "description": "Majestic Rajasthani palace aesthetics with deep emerald green velvet, antique gold leaf archways, and botanical jharokha borders.",
        "preview_image": "/velvet_invitation_chest.jpg",
        "mode": "dark",
        "style": "Royal",
        "mood": "Formal",
        "typography": "font-serif",
        "background_style": "emerald-palace-radial",
        "decoration_style": "GOLD_SPARKLES_EMERALD",
        "animation_style": "traditional",
        "tags": ["ROYAL", "DARK", "TRADITIONAL"],
        "recommended_occasions": ["WEDDING", "VIVAH", "ROYAL_WEDDING"],
        "is_recommended": False,
    },
    {
        "id": "haldi-marigold-celebration",
        "celebration_type": "HALDI",
        "name": "Marigold Celebration",
        "tagline": "Vibrant Saffron, Marigold Garlands & Brass Urlis",
        "description": "Sunny, joyful celebration card radiating yellow marigold garlands, traditional turmeric paste bowls, and festive courtyard sunshine.",
        "preview_image": "/romantic_3d_wedding_stage.jpg",
        "mode": "vibrant",
        "style": "Traditional",
        "mood": "Joyful",
        "typography": "font-serif",
        "background_style": "sunshine-haldi-radial",
        "decoration_style": "MARIGOLD_PETALS_DIYAS",
        "animation_style": "festive",
        "tags": ["VIBRANT", "TRADITIONAL", "RECOMMENDED"],
        "recommended_occasions": ["HALDI", "HALDI_CEREMONY", "UBTAN"],
        "is_recommended": True,
    },
    {
        "id": "mehndi-emerald-henna",
        "celebration_type": "MEHNDI",
        "name": "Emerald Henna & Peacocks",
        "tagline": "Mehndi Green, Teal, Gold & Intricate Henna Arches",
        "description": "Artistic and festive Mehndi stationery celebrating traditional Indian henna patterns, dancing peacock motifs, and mustard gold accents.",
        "preview_image": "/velvet_invitation_chest.jpg",
        "mode": "vibrant",
        "style": "Traditional",
        "mood": "Joyful",
        "typography": "font-serif",
        "background_style": "emerald-palace-radial",
        "decoration_style": "MARIGOLD_PETALS_DIYAS",
        "animation_style": "festive",
        "tags": ["TRADITIONAL", "FLORAL", "RECOMMENDED"],
        "recommended_occasions": ["MEHNDI", "MEHNDI_CEREMONY", "HENNA_NIGHT"],
        "is_recommended": True,
    },
    {
        "id": "sangeet-midnight-bollywood",
        "celebration_type": "SANGEET",
        "name": "Midnight Bollywood & Stage Lights",
        "tagline": "Midnight Purple, Gold Spotlight & Dholak Rhythms",
        "description": "High-energy, glamorous musical night card with spotlight beams, golden sparkles, dholak silhouettes, and festive night-time party vibes.",
        "preview_image": "/romantic_3d_invitation_hero.jpg",
        "mode": "luxury-dark",
        "style": "Luxury",
        "mood": "Glamorous",
        "typography": "font-serif",
        "background_style": "sangeet-purple-radial",
        "decoration_style": "CONFETTI_BALLOONS",
        "animation_style": "festive",
        "tags": ["DARK", "GLAMOROUS", "RECOMMENDED"],
        "recommended_occasions": ["SANGEET", "MUSICAL_NIGHT", "DANCE_NIGHT"],
        "is_recommended": True,
    },
    {
        "id": "reception-midnight-grandeur",
        "celebration_type": "RECEPTION",
        "name": "Midnight Grandeur & Chandeliers",
        "tagline": "Royal Navy, Champagne Gold & Crystal Chandeliers",
        "description": "Ultra-luxurious evening reception card with sparkling crystal chandeliers, champagne glasses, and polished formal ballroom aesthetics.",
        "preview_image": "/romantic_3d_invitation_hero.jpg",
        "mode": "luxury-dark",
        "style": "Luxury",
        "mood": "Formal",
        "typography": "font-serif",
        "background_style": "reception-navy-radial",
        "decoration_style": "ROSE_PETALS_HEARTS",
        "animation_style": "romantic",
        "tags": ["DARK", "LUXURY", "FORMAL", "RECOMMENDED"],
        "recommended_occasions": ["RECEPTION", "WEDDING_RECEPTION", "GALA_DINNER"],
        "is_recommended": True,
    },
    {
        "id": "babyshower-little-wonder",
        "celebration_type": "BABY_SHOWER",
        "name": "Little Wonder & Pastel Clouds",
        "tagline": "Powder Blue, Blush Pink, Lavender & Teddy Bears",
        "description": "Soft, innocent baby shower invitation adorned with fluffy pastel clouds, golden crescent moon, nursery stars, and teddy bear warmth.",
        "preview_image": "/velvet_invitation_chest.jpg",
        "mode": "pastel",
        "style": "Modern",
        "mood": "Playful",
        "typography": "font-serif",
        "background_style": "baby-pastel-radial",
        "decoration_style": "CONFETTI_BALLOONS",
        "animation_style": "playful",
        "tags": ["PASTEL", "BABY", "RECOMMENDED"],
        "recommended_occasions": ["BABY_SHOWER", "GODH_BHARAI", "BABY_ARRIVAL"],
        "is_recommended": True,
    },
    {
        "id": "mundan-sacred-beginnings",
        "celebration_type": "MUNDAN",
        "name": "Sacred Beginnings & Blessings",
        "tagline": "Cream, Saffron, Glowing Diyas & Temple Arches",
        "description": "Devotional Indian Mundan ceremony design with sandalwood tilak, temple bells, brass diyas, and sacred Sanskrit Vedic invocations.",
        "preview_image": "/velvet_invitation_chest.jpg",
        "mode": "light",
        "style": "Traditional",
        "mood": "Spiritual",
        "typography": "font-serif",
        "background_style": "sacred-marigold-radial",
        "decoration_style": "LOTUS_BLOSSOMS",
        "animation_style": "traditional",
        "tags": ["TRADITIONAL", "BABY", "LIGHT", "RECOMMENDED"],
        "recommended_occasions": ["MUNDAN", "CHUDAKARANA", "TONSURE", "JADULA"],
        "is_recommended": True,
    },
    {
        "id": "birthday-celebration-burst",
        "celebration_type": "BIRTHDAY",
        "name": "Celebration Burst & Confetti",
        "tagline": "Golden Confetti, Balloons & Vibrant Lighting",
        "description": "High-energy party atmosphere with floating metallic balloons, exploding golden confetti, and birthday starbursts.",
        "preview_image": "/romantic_3d_invitation_hero.jpg",
        "mode": "vibrant",
        "style": "Festive",
        "mood": "Joyful",
        "typography": "font-sans",
        "background_style": "party-stardust-radial",
        "decoration_style": "CONFETTI_BALLOONS",
        "animation_style": "festive",
        "tags": ["FESTIVE", "VIBRANT", "RECOMMENDED"],
        "recommended_occasions": ["BIRTHDAY", "TEEN_BIRTHDAY", "SURPRISE_PARTY"],
        "is_recommended": True,
    },
    {
        "id": "housewarming-griha-pravesh",
        "celebration_type": "HOUSEWARMING",
        "name": "Griha Pravesh & Shubh Rangoli",
        "tagline": "Terracotta, Gold, Mango Toran & Sacred Kalash",
        "description": "Auspicious new home blessings card with auspicious Kalash, glowing brass diyas, sacred Swastik, and traditional floral entrance toran.",
        "preview_image": "/velvet_invitation_chest.jpg",
        "mode": "light",
        "style": "Traditional",
        "mood": "Spiritual",
        "typography": "font-serif",
        "background_style": "sacred-marigold-radial",
        "decoration_style": "FESTIVE_DIYAS",
        "animation_style": "traditional",
        "tags": ["TRADITIONAL", "LIGHT", "RECOMMENDED"],
        "recommended_occasions": ["GRIHA_PRAVESH", "HOUSEWARMING", "HOME_BLESSING"],
        "is_recommended": True,
    },
    {
        "id": "corporate-business-conference",
        "celebration_type": "CORPORATE",
        "name": "Business Conference & Summit",
        "tagline": "Midnight Navy, Platinum Steel & Minimalist Skyline",
        "description": "Executive corporate card with sleek architectural geometry, platinum reflections, and clean typography tailored for leadership summits.",
        "preview_image": "/velvet_invitation_chest.jpg",
        "mode": "luxury-dark",
        "style": "Modern",
        "mood": "Formal",
        "typography": "font-sans",
        "background_style": "corporate-navy-radial",
        "decoration_style": "GEOMETRIC_TECH_STREAKS",
        "animation_style": "professional",
        "tags": ["CORPORATE", "DARK", "MODERN", "RECOMMENDED"],
        "recommended_occasions": ["CORPORATE", "CONFERENCE", "BUSINESS_SUMMIT", "SEMINAR"],
        "is_recommended": True,
    },
    {
        "id": "celebration-universal-modern",
        "celebration_type": "OTHER",
        "name": "Modern Universal Celebration",
        "tagline": "Abstract Radiant Bokeh & Golden Ambient Lights",
        "description": "An elegant, versatile design with glowing ambient bokeh, modern serif typography, and balanced celebratory aesthetics for any gathering.",
        "preview_image": "/romantic_3d_invitation_hero.jpg",
        "mode": "luxury-dark",
        "style": "Modern",
        "mood": "Elegant",
        "typography": "font-serif",
        "background_style": "romantic-wine-radial",
        "decoration_style": "GOLD_SPARKLES_EMERALD",
        "animation_style": "romantic",
        "tags": ["MODERN", "ROYAL", "RECOMMENDED"],
        "recommended_occasions": ["OTHER", "REUNION", "FAMILY_REUNION", "CELEBRATION"],
        "is_recommended": True,
    },
]


class ThemeCatalogService:
    @staticmethod
    def get_themes(celebration_type: Optional[str] = None) -> List[Dict[str, Any]]:
        if not celebration_type:
            return MASTER_BACKEND_THEMES

        c_type = celebration_type.upper().strip()
        filtered = [
            t for t in MASTER_BACKEND_THEMES
            if t["celebration_type"] == c_type or c_type in [o.upper() for o in t.get("recommended_occasions", [])]
        ]
        return filtered if filtered else MASTER_BACKEND_THEMES

    @staticmethod
    def get_theme_by_id(theme_id: str) -> Dict[str, Any]:
        for t in MASTER_BACKEND_THEMES:
            if t["id"] == theme_id:
                return t
        return MASTER_BACKEND_THEMES[0]
