/**
 * NIMANTRAN AI — MASTER EVENT-SPECIFIC 3D INVITATION CARD THEME CATALOG
 * 
 * Supports 3D physical layered appearance, light & dark modes, event-specific visual identity,
 * decorative motifs, metallic borders, lighting styles, textures, and dynamic text overlays.
 * 
 * Zero hardcoded text in template artwork — 100% dynamic event data driven.
 */

export type ThemeImageSource = 'LOCAL' | 'REMOTE' | 'AI_GENERATED' | 'USER_UPLOADED';

export type ThemeMode = 'light' | 'dark' | 'luxury-dark' | 'pastel' | 'vibrant';

export type ThemeStyle = 'Traditional' | 'Royal' | 'Modern' | 'Floral' | 'Minimal' | 'Luxury' | 'Festive' | 'Romantic';

export type ThemeMood = 'Romantic' | 'Elegant' | 'Joyful' | 'Glamorous' | 'Formal' | 'Spiritual' | 'Playful';

export interface ThemeColorPalette {
  canvasBg: string;
  surfaceBg: string;
  surfaceElevated: string;
  primary: string;
  primaryHover: string;
  primaryText: string;
  accent: string;
  accentSoft: string;
  textHeading: string;
  textBody: string;
  textMuted: string;
  borderSoft: string;
  borderAccent: string;
  gradientHeader: string;
  badgeBg: string;
  badgeText: string;
}

export interface CelebrationTheme {
  id: string;
  celebrationType: string;
  name: string;
  tagline: string;
  description: string;
  previewImage: string;
  thumbnailImage: string;
  imageSource: ThemeImageSource;
  mode: ThemeMode;
  style: ThemeStyle;
  mood: ThemeMood;
  texture: 'paper-embossed' | 'velvet' | 'silk' | 'marble' | 'watercolor' | 'metallic';
  borderStyle: string;
  colorPalette: ThemeColorPalette;
  typography: 'font-serif' | 'font-sans';
  backgroundStyle: string;
  decorationStyle: string;
  animationStyle: 'romantic' | 'festive' | 'traditional' | 'professional' | 'minimal' | 'playful';
  icon: string;
  badgeIcon: string;
  badgeLabel: string;
  tags: string[];
  recommendedOccasions: string[];
  isRecommendedDefault?: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// FILTER OPTIONS FOR STEP 3
// ─────────────────────────────────────────────────────────────────────────────
export const THEME_FILTER_TAGS = [
  { id: 'ALL', label: 'All Designs', icon: '✨' },
  { id: 'RECOMMENDED', label: 'Recommended', icon: '⭐' },
  { id: 'LIGHT', label: 'Light & Ivory', icon: '☀️' },
  { id: 'DARK', label: 'Dark Luxury', icon: '🌙' },
  { id: 'ROYAL', label: 'Royal Heritage', icon: '👑' },
  { id: 'ROMANTIC', label: 'Romantic & Floral', icon: '🌹' },
  { id: 'VIBRANT', label: 'Joyful & Vibrant', icon: '🌼' },
  { id: 'TRADITIONAL', label: 'Sacred & Traditional', icon: '🪷' },
  { id: 'GLAMOROUS', label: 'Glamour & Night', icon: '🍸' },
  { id: 'PASTEL', label: 'Pastel & Cute', icon: '🧸' },
  { id: 'CORPORATE', label: 'Corporate & Summit', icon: '💼' },
];

export const THEME_MODE_FILTERS = [
  { id: 'ALL', label: 'All Modes' },
  { id: 'light', label: 'Light' },
  { id: 'dark', label: 'Dark' },
  { id: 'luxury-dark', label: 'Luxury Dark' },
  { id: 'pastel', label: 'Pastel' },
  { id: 'vibrant', label: 'Vibrant' },
];

export const THEME_STYLE_FILTERS = [
  { id: 'ALL', label: 'All Styles' },
  { id: 'Royal', label: 'Royal' },
  { id: 'Traditional', label: 'Traditional' },
  { id: 'Romantic', label: 'Romantic' },
  { id: 'Floral', label: 'Floral' },
  { id: 'Modern', label: 'Modern' },
  { id: 'Luxury', label: 'Luxury' },
  { id: 'Festive', label: 'Festive' },
  { id: 'Minimal', label: 'Minimal' },
];

// ─────────────────────────────────────────────────────────────────────────────
// MASTER THEME CATALOG (35+ EVENT-SPECIFIC 3D THEMES)
// ─────────────────────────────────────────────────────────────────────────────
export const MASTER_THEME_CATALOG: CelebrationTheme[] = [
  // ─── 1. WEDDING / VIVAH THEMES ──────────────────────────────────────────
  {
    id: 'wedding-royal-heritage',
    celebrationType: 'WEDDING',
    name: '01 — Royal Heritage',
    tagline: 'Light Ivory Paper, Rich Antique Gold & Burgundy Flora',
    description: 'Flagship wedding stationery with Indian palace arches, embossed golden filigree, realistic layered paper depth, and majestic burgundy floral accents.',
    previewImage: '/romantic_3d_wedding_stage.jpg',
    thumbnailImage: '/romantic_3d_wedding_stage.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Royal',
    mood: 'Romantic',
    texture: 'paper-embossed',
    borderStyle: 'embossed-gold-filigree',
    colorPalette: {
      canvasBg: '#FFFDFC',
      surfaceBg: '#FAF7F2',
      surfaceElevated: '#F5EFEB',
      primary: '#80102A',
      primaryHover: '#600C20',
      primaryText: '#FFFFFF',
      accent: '#C59A4E',
      accentSoft: 'rgba(197, 154, 78, 0.15)',
      textHeading: '#3B2314',
      textBody: '#5C4033',
      textMuted: '#8B7366',
      borderSoft: '#E6D7C3',
      borderAccent: '#C59A4E',
      gradientHeader: 'linear-gradient(135deg, #80102A 0%, #C59A4E 100%)',
      badgeBg: 'rgba(197, 154, 78, 0.2)',
      badgeText: '#80102A',
    },
    typography: 'font-serif',
    backgroundStyle: 'ivory-palace-radial',
    decorationStyle: 'ROYAL_MANDAP_GARLANDS',
    animationStyle: 'traditional',
    icon: '👑',
    badgeIcon: '👑',
    badgeLabel: 'WEDDING • FLAGSHIP',
    tags: ['ROYAL', 'LIGHT', 'TRADITIONAL', 'RECOMMENDED'],
    recommendedOccasions: ['WEDDING', 'VIVAH', 'MARRIAGE', 'GRAND_WEDDING'],
    isRecommendedDefault: true,
  },
  {
    id: 'wedding-midnight-royal',
    celebrationType: 'WEDDING',
    name: '02 — Midnight Royal',
    tagline: 'Deep Burgundy Velvet & Metallic Gold Foil',
    description: 'Dramatic dark luxury wedding invitation with velvet midnight background, metallic champagne gold floral frames, and cinematic candlelight.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Luxury',
    mood: 'Glamorous',
    texture: 'velvet',
    borderStyle: 'metallic-gold-foil',
    colorPalette: {
      canvasBg: '#0D0508',
      surfaceBg: 'rgba(28, 10, 18, 0.94)',
      surfaceElevated: 'rgba(48, 16, 30, 0.96)',
      primary: '#9E2A4B',
      primaryHover: '#7E1D3A',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#FFF8E7',
      textBody: '#F5E6D3',
      textMuted: '#D8BFA6',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #FFF8E7 0%, #F59E0B 50%, #9E2A4B 100%)',
      badgeBg: 'rgba(245, 158, 11, 0.2)',
      badgeText: '#FDE68A',
    },
    typography: 'font-serif',
    backgroundStyle: 'romantic-wine-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '🌹',
    badgeIcon: '🌹',
    badgeLabel: 'WEDDING • LUXURY DARK',
    tags: ['DARK', 'LUXURY', 'ROMANTIC'],
    recommendedOccasions: ['WEDDING', 'VIVAH', 'RECEPTION'],
  },
  {
    id: 'wedding-emerald-palace',
    celebrationType: 'WEDDING',
    name: '03 — Emerald Palace',
    tagline: 'Imperial Forest Green & Royal Gold Filigree',
    description: 'Majestic Rajasthani palace aesthetics with deep emerald green velvet, antique gold leaf archways, and botanical jharokha borders.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'dark',
    style: 'Royal',
    mood: 'Formal',
    texture: 'silk',
    borderStyle: 'palace-arch',
    colorPalette: {
      canvasBg: '#04140D',
      surfaceBg: 'rgba(8, 36, 24, 0.94)',
      surfaceElevated: 'rgba(12, 56, 38, 0.96)',
      primary: '#059669',
      primaryHover: '#047857',
      primaryText: '#FFFFFF',
      accent: '#FBBF24',
      accentSoft: 'rgba(251, 191, 36, 0.2)',
      textHeading: '#ECFDF5',
      textBody: '#D1FAE5',
      textMuted: '#A7F3D0',
      borderSoft: 'rgba(251, 191, 36, 0.3)',
      borderAccent: '#FBBF24',
      gradientHeader: 'linear-gradient(135deg, #ECFDF5 0%, #FBBF24 50%, #059669 100%)',
      badgeBg: 'rgba(5, 150, 105, 0.3)',
      badgeText: '#6EE7B7',
    },
    typography: 'font-serif',
    backgroundStyle: 'emerald-palace-radial',
    decorationStyle: 'GOLD_SPARKLES_EMERALD',
    animationStyle: 'traditional',
    icon: '🏰',
    badgeIcon: '🏰',
    badgeLabel: 'WEDDING • EMERALD',
    tags: ['ROYAL', 'DARK', 'TRADITIONAL'],
    recommendedOccasions: ['WEDDING', 'VIVAH', 'ROYAL_WEDDING'],
  },
  {
    id: 'wedding-blush-romance',
    celebrationType: 'WEDDING',
    name: '04 — Blush Romance',
    tagline: 'Ivory, Blush Roses & Rose Gold Foil',
    description: 'Soft romantic stationery with English garden blush roses, delicate rose gold filigree borders, and warm champagne lighting.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'pastel',
    style: 'Floral',
    mood: 'Romantic',
    texture: 'watercolor',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#FFF8F6',
      surfaceBg: '#FDF0ED',
      surfaceElevated: '#F9E4DF',
      primary: '#BE185D',
      primaryHover: '#9D174D',
      primaryText: '#FFFFFF',
      accent: '#FB7185',
      accentSoft: 'rgba(251, 113, 133, 0.15)',
      textHeading: '#4C0519',
      textBody: '#831843',
      textMuted: '#9F1239',
      borderSoft: '#FBCFE8',
      borderAccent: '#F43F5E',
      gradientHeader: 'linear-gradient(135deg, #BE185D 0%, #FB7185 100%)',
      badgeBg: 'rgba(251, 113, 133, 0.2)',
      badgeText: '#BE185D',
    },
    typography: 'font-serif',
    backgroundStyle: 'blush-pastel-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '🌸',
    badgeIcon: '🌸',
    badgeLabel: 'WEDDING • BLUSH',
    tags: ['ROMANTIC', 'FLORAL', 'PASTEL', 'LIGHT'],
    recommendedOccasions: ['WEDDING', 'VIVAH', 'SAGAI', 'ENGAGEMENT'],
  },
  {
    id: 'wedding-pastel-garden',
    celebrationType: 'WEDDING',
    name: '05 — Pastel Garden',
    tagline: 'Sage, Peach, Cream & Botanical Florals',
    description: 'Earthy botanical elegance featuring sage leaves, peach blossoms, deckled paper texture, and soft natural daylighting.',
    previewImage: '/romantic_3d_wedding_stage.jpg',
    thumbnailImage: '/romantic_3d_wedding_stage.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Floral',
    mood: 'Elegant',
    texture: 'paper-embossed',
    borderStyle: 'minimal-dual',
    colorPalette: {
      canvasBg: '#F7FAF7',
      surfaceBg: '#EFF5EF',
      surfaceElevated: '#E2EDE2',
      primary: '#2D5A27',
      primaryHover: '#1E3F1A',
      primaryText: '#FFFFFF',
      accent: '#E07A5F',
      accentSoft: 'rgba(224, 122, 95, 0.15)',
      textHeading: '#1B3517',
      textBody: '#354F31',
      textMuted: '#587354',
      borderSoft: '#CCDCCC',
      borderAccent: '#E07A5F',
      gradientHeader: 'linear-gradient(135deg, #2D5A27 0%, #E07A5F 100%)',
      badgeBg: 'rgba(45, 90, 39, 0.15)',
      badgeText: '#2D5A27',
    },
    typography: 'font-serif',
    backgroundStyle: 'sage-garden-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '🌿',
    badgeIcon: '🌿',
    badgeLabel: 'WEDDING • BOTANICAL',
    tags: ['FLORAL', 'LIGHT', 'MODERN'],
    recommendedOccasions: ['WEDDING', 'DAY_WEDDING', 'DESTINATION_WEDDING'],
  },
  {
    id: 'wedding-burgundy-luxe',
    celebrationType: 'WEDDING',
    name: '06 — Burgundy Luxe',
    tagline: 'Deep Wine, Burgundy & Heavy Gold Foil',
    description: 'Opulent royal wine and burgundy tones paired with heavy sculpted gold foil borders and cinematic studio lighting.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Royal',
    mood: 'Glamorous',
    texture: 'velvet',
    borderStyle: 'metallic-gold-foil',
    colorPalette: {
      canvasBg: '#140308',
      surfaceBg: 'rgba(38, 8, 16, 0.94)',
      surfaceElevated: 'rgba(64, 12, 26, 0.96)',
      primary: '#9F1239',
      primaryHover: '#881337',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#FFF1F2',
      textBody: '#FFE4E6',
      textMuted: '#FECDD3',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #FFF1F2 0%, #F59E0B 50%, #9F1239 100%)',
      badgeBg: 'rgba(159, 18, 57, 0.3)',
      badgeText: '#FDA4AF',
    },
    typography: 'font-serif',
    backgroundStyle: 'romantic-wine-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '🍷',
    badgeIcon: '🍷',
    badgeLabel: 'WEDDING • BURGUNDY',
    tags: ['ROYAL', 'DARK', 'LUXURY'],
    recommendedOccasions: ['WEDDING', 'RECEPTION', 'VIVAH'],
  },

  // ─── 2. ENGAGEMENT / ROKA / SAGAI ───────────────────────────────────────
  {
    id: 'engagement-champagne-romance',
    celebrationType: 'ENGAGEMENT',
    name: 'Champagne Romance',
    tagline: 'Sparkling Champagne, Ivory & Rose Gold Bands',
    description: 'Luminous engagement card with interlocking diamond ring motifs, floating champagne bubbles, and rose gold accents.',
    previewImage: '/romantic_3d_envelope_rings.jpg',
    thumbnailImage: '/romantic_3d_envelope_rings.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Romantic',
    mood: 'Romantic',
    texture: 'paper-embossed',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#FFFDF9',
      surfaceBg: '#FAF5ED',
      surfaceElevated: '#F4ECE0',
      primary: '#B45309',
      primaryHover: '#92400E',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.15)',
      textHeading: '#451A03',
      textBody: '#78350F',
      textMuted: '#92400E',
      borderSoft: '#E6D7C3',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #B45309 0%, #F59E0B 100%)',
      badgeBg: 'rgba(245, 158, 11, 0.2)',
      badgeText: '#B45309',
    },
    typography: 'font-serif',
    backgroundStyle: 'champagne-glow-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '💍',
    badgeIcon: '💍',
    badgeLabel: 'ENGAGEMENT • ROMANCE',
    tags: ['ROMANTIC', 'LIGHT', 'RECOMMENDED'],
    recommendedOccasions: ['ENGAGEMENT', 'SAGAI', 'ROKA', 'RING_CEREMONY'],
    isRecommendedDefault: true,
  },
  {
    id: 'engagement-diamond-luxe',
    celebrationType: 'ENGAGEMENT',
    name: 'Diamond Luxe & Midnight',
    tagline: 'Matte Black, Diamond Prisms & Silver Platinum',
    description: 'Contemporary luxury ring ceremony card with dramatic black velvet background, radiant solitaire diamond facets, and platinum highlights.',
    previewImage: '/romantic_3d_envelope_rings.jpg',
    thumbnailImage: '/romantic_3d_envelope_rings.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Modern',
    mood: 'Glamorous',
    texture: 'velvet',
    borderStyle: 'minimal-dual',
    colorPalette: {
      canvasBg: '#090A0F',
      surfaceBg: 'rgba(18, 20, 30, 0.94)',
      surfaceElevated: 'rgba(28, 32, 48, 0.96)',
      primary: '#3B82F6',
      primaryHover: '#2563EB',
      primaryText: '#FFFFFF',
      accent: '#E2E8F0',
      accentSoft: 'rgba(226, 232, 240, 0.2)',
      textHeading: '#F8FAFC',
      textBody: '#E2E8F0',
      textMuted: '#94A3B8',
      borderSoft: 'rgba(226, 232, 240, 0.3)',
      borderAccent: '#E2E8F0',
      gradientHeader: 'linear-gradient(135deg, #F8FAFC 0%, #94A3B8 50%, #3B82F6 100%)',
      badgeBg: 'rgba(59, 130, 246, 0.2)',
      badgeText: '#93C5FD',
    },
    typography: 'font-serif',
    backgroundStyle: 'platinum-night-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '💎',
    badgeIcon: '💎',
    badgeLabel: 'ENGAGEMENT • DIAMOND',
    tags: ['DARK', 'LUXURY', 'MODERN'],
    recommendedOccasions: ['ENGAGEMENT', 'RING_CEREMONY', 'SAGAI'],
  },

  // ─── 3. HALDI CEREMONY ──────────────────────────────────────────────────
  {
    id: 'haldi-marigold-celebration',
    celebrationType: 'HALDI',
    name: 'Marigold Celebration',
    tagline: 'Vibrant Saffron, Marigold Garlands & Brass Urlis',
    description: 'Sunny, joyful celebration card radiating yellow marigold garlands, traditional turmeric paste bowls, floral torans, and festive Indian courtyard sunshine.',
    previewImage: '/romantic_3d_wedding_stage.jpg',
    thumbnailImage: '/romantic_3d_wedding_stage.jpg',
    imageSource: 'LOCAL',
    mode: 'vibrant',
    style: 'Traditional',
    mood: 'Joyful',
    texture: 'paper-embossed',
    borderStyle: 'embossed-gold-filigree',
    colorPalette: {
      canvasBg: '#FFFBEB',
      surfaceBg: '#FEF3C7',
      surfaceElevated: '#FDE68A',
      primary: '#D97706',
      primaryHover: '#B45309',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.25)',
      textHeading: '#78350F',
      textBody: '#92400E',
      textMuted: '#B45309',
      borderSoft: '#FCD34D',
      borderAccent: '#D97706',
      gradientHeader: 'linear-gradient(135deg, #D97706 0%, #F59E0B 100%)',
      badgeBg: 'rgba(217, 119, 6, 0.2)',
      badgeText: '#B45309',
    },
    typography: 'font-serif',
    backgroundStyle: 'sunshine-haldi-radial',
    decorationStyle: 'MARIGOLD_PETALS_DIYAS',
    animationStyle: 'festive',
    icon: '🌼',
    badgeIcon: '🌼',
    badgeLabel: 'HALDI • SUNSHINE',
    tags: ['VIBRANT', 'TRADITIONAL', 'RECOMMENDED'],
    recommendedOccasions: ['HALDI', 'HALDI_CEREMONY', 'UBTAN'],
    isRecommendedDefault: true,
  },
  {
    id: 'haldi-turmeric-garden',
    celebrationType: 'HALDI',
    name: 'Turmeric Garden & Floral Toran',
    tagline: 'Bright Sunshine Yellow, Peach & Leaf Green',
    description: 'Vibrant outdoor garden theme with fresh turmeric blossoms, mango leaf torans, and playful yellow floral petals.',
    previewImage: '/romantic_3d_wedding_stage.jpg',
    thumbnailImage: '/romantic_3d_wedding_stage.jpg',
    imageSource: 'LOCAL',
    mode: 'vibrant',
    style: 'Floral',
    mood: 'Joyful',
    texture: 'watercolor',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#FEFCE8',
      surfaceBg: '#FEF9C3',
      surfaceElevated: '#FEF08A',
      primary: '#CA8A04',
      primaryHover: '#A16207',
      primaryText: '#FFFFFF',
      accent: '#16A34A',
      accentSoft: 'rgba(22, 163, 74, 0.2)',
      textHeading: '#713F12',
      textBody: '#854D0E',
      textMuted: '#A16207',
      borderSoft: '#FDE047',
      borderAccent: '#CA8A04',
      gradientHeader: 'linear-gradient(135deg, #CA8A04 0%, #16A34A 100%)',
      badgeBg: 'rgba(202, 138, 4, 0.2)',
      badgeText: '#A16207',
    },
    typography: 'font-serif',
    backgroundStyle: 'sunshine-haldi-radial',
    decorationStyle: 'MARIGOLD_PETALS_DIYAS',
    animationStyle: 'festive',
    icon: '🌻',
    badgeIcon: '🌻',
    badgeLabel: 'HALDI • FLORAL',
    tags: ['VIBRANT', 'FLORAL'],
    recommendedOccasions: ['HALDI', 'HALDI_CEREMONY'],
  },

  // ─── 4. MEHNDI CELEBRATIONS ─────────────────────────────────────────────
  {
    id: 'mehndi-emerald-henna',
    celebrationType: 'MEHNDI',
    name: 'Emerald Henna & Peacocks',
    tagline: 'Mehndi Green, Teal, Gold & Intricate Henna Arches',
    description: 'Artistic and festive Mehndi stationery celebrating traditional Indian henna patterns, dancing peacock motifs, and mustard gold accents.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'vibrant',
    style: 'Traditional',
    mood: 'Joyful',
    texture: 'silk',
    borderStyle: 'palace-arch',
    colorPalette: {
      canvasBg: '#061A12',
      surfaceBg: 'rgba(10, 44, 30, 0.94)',
      surfaceElevated: 'rgba(16, 68, 46, 0.96)',
      primary: '#0D9488',
      primaryHover: '#0F766E',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#F0FDFA',
      textBody: '#CCFBF1',
      textMuted: '#99F6E4',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #F0FDFA 0%, #F59E0B 50%, #0D9488 100%)',
      badgeBg: 'rgba(13, 148, 136, 0.3)',
      badgeText: '#5EEAD4',
    },
    typography: 'font-serif',
    backgroundStyle: 'emerald-palace-radial',
    decorationStyle: 'MARIGOLD_PETALS_DIYAS',
    animationStyle: 'festive',
    icon: '🦚',
    badgeIcon: '🦚',
    badgeLabel: 'MEHNDI • HENNA',
    tags: ['TRADITIONAL', 'FLORAL', 'RECOMMENDED'],
    recommendedOccasions: ['MEHNDI', 'MEHNDI_CEREMONY', 'HENNA_NIGHT'],
    isRecommendedDefault: true,
  },

  // ─── 5. SANGEET & MUSICAL NIGHT ─────────────────────────────────────────
  {
    id: 'sangeet-midnight-bollywood',
    celebrationType: 'SANGEET',
    name: 'Midnight Bollywood & Stage Lights',
    tagline: 'Midnight Purple, Gold Spotlight & Dholak Rhythms',
    description: 'High-energy, glamorous musical night card with spotlight beams, golden sparkles, dholak silhouettes, and festive night-time party vibes.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Luxury',
    mood: 'Glamorous',
    texture: 'velvet',
    borderStyle: 'metallic-gold-foil',
    colorPalette: {
      canvasBg: '#0E0417',
      surfaceBg: 'rgba(28, 8, 48, 0.94)',
      surfaceElevated: 'rgba(48, 14, 80, 0.96)',
      primary: '#7C3AED',
      primaryHover: '#6D28D9',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#FAF5FF',
      textBody: '#F3E8FF',
      textMuted: '#D8B4FE',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #FAF5FF 0%, #F59E0B 50%, #7C3AED 100%)',
      badgeBg: 'rgba(124, 58, 237, 0.3)',
      badgeText: '#C4B5FD',
    },
    typography: 'font-serif',
    backgroundStyle: 'sangeet-purple-radial',
    decorationStyle: 'CONFETTI_BALLOONS',
    animationStyle: 'festive',
    icon: '🪕',
    badgeIcon: '🪕',
    badgeLabel: 'SANGEET • GLAMOUR',
    tags: ['DARK', 'GLAMOROUS', 'RECOMMENDED'],
    recommendedOccasions: ['SANGEET', 'MUSICAL_NIGHT', 'DANCE_NIGHT'],
    isRecommendedDefault: true,
  },

  // ─── 6. WEDDING RECEPTION ───────────────────────────────────────────────
  {
    id: 'reception-midnight-grandeur',
    celebrationType: 'RECEPTION',
    name: 'Midnight Grandeur & Chandeliers',
    tagline: 'Royal Navy, Champagne Gold & Crystal Chandeliers',
    description: 'Ultra-luxurious evening reception card with sparkling crystal chandeliers, champagne glasses, and polished formal ballroom aesthetics.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Luxury',
    mood: 'Formal',
    texture: 'silk',
    borderStyle: 'metallic-gold-foil',
    colorPalette: {
      canvasBg: '#050B14',
      surfaceBg: 'rgba(10, 22, 40, 0.94)',
      surfaceElevated: 'rgba(18, 38, 68, 0.96)',
      primary: '#1D4ED8',
      primaryHover: '#1E40AF',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#EFF6FF',
      textBody: '#DBEAFE',
      textMuted: '#93C5FD',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #EFF6FF 0%, #F59E0B 50%, #1D4ED8 100%)',
      badgeBg: 'rgba(29, 78, 216, 0.3)',
      badgeText: '#BFDBFE',
    },
    typography: 'font-serif',
    backgroundStyle: 'reception-navy-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '🥂',
    badgeIcon: '🥂',
    badgeLabel: 'RECEPTION • FORMAL',
    tags: ['DARK', 'LUXURY', 'FORMAL', 'RECOMMENDED'],
    recommendedOccasions: ['RECEPTION', 'WEDDING_RECEPTION', 'GALA_DINNER'],
    isRecommendedDefault: true,
  },

  // ─── 7. BABY SHOWER & GODH BHARAI ───────────────────────────────────────
  {
    id: 'babyshower-little-wonder',
    celebrationType: 'BABY_SHOWER',
    name: 'Little Wonder & Pastel Clouds',
    tagline: 'Powder Blue, Blush Pink, Lavender & Teddy Bears',
    description: 'Soft, innocent baby shower invitation adorned with fluffy pastel clouds, golden crescent moon, nursery stars, and teddy bear warmth.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'pastel',
    style: 'Modern',
    mood: 'Playful',
    texture: 'watercolor',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#FAF5FF',
      surfaceBg: '#F3E8FF',
      surfaceElevated: '#E9D5FF',
      primary: '#9333EA',
      primaryHover: '#7E22CE',
      primaryText: '#FFFFFF',
      accent: '#EC4899',
      accentSoft: 'rgba(236, 72, 153, 0.15)',
      textHeading: '#581C87',
      textBody: '#6B21A8',
      textMuted: '#7E22CE',
      borderSoft: '#D8B4FE',
      borderAccent: '#EC4899',
      gradientHeader: 'linear-gradient(135deg, #9333EA 0%, #EC4899 100%)',
      badgeBg: 'rgba(147, 51, 234, 0.15)',
      badgeText: '#9333EA',
    },
    typography: 'font-serif',
    backgroundStyle: 'baby-pastel-radial',
    decorationStyle: 'CONFETTI_BALLOONS',
    animationStyle: 'playful',
    icon: '🧸',
    badgeIcon: '🧸',
    badgeLabel: 'BABY SHOWER • PASTEL',
    tags: ['PASTEL', 'BABY', 'RECOMMENDED'],
    recommendedOccasions: ['BABY_SHOWER', 'GODH_BHARAI', 'BABY_ARRIVAL'],
    isRecommendedDefault: true,
  },
  {
    id: 'namkaran-sacred-cradle',
    celebrationType: 'BABY_SHOWER',
    name: 'Namkaran & Sacred Cradle',
    tagline: 'Baby Blue, Cream, Gold & Traditional Cradle',
    description: 'Auspicious baby naming ceremony card with sacred floral cradle, blessing diyas, baby footprints, and Sanskrit prayers.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Traditional',
    mood: 'Spiritual',
    texture: 'paper-embossed',
    borderStyle: 'embossed-gold-filigree',
    colorPalette: {
      canvasBg: '#F0F9FF',
      surfaceBg: '#E0F2FE',
      surfaceElevated: '#BAE6FD',
      primary: '#0284C7',
      primaryHover: '#0369A1',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#0C4A6E',
      textBody: '#075985',
      textMuted: '#0284C7',
      borderSoft: '#7DD3FC',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #0284C7 0%, #F59E0B 100%)',
      badgeBg: 'rgba(2, 132, 199, 0.15)',
      badgeText: '#0369A1',
    },
    typography: 'font-serif',
    backgroundStyle: 'baby-pastel-radial',
    decorationStyle: 'LOTUS_BLOSSOMS',
    animationStyle: 'traditional',
    icon: '👶',
    badgeIcon: '👶',
    badgeLabel: 'NAMKARAN • SACRED',
    tags: ['TRADITIONAL', 'BABY', 'LIGHT'],
    recommendedOccasions: ['NAMKARAN', 'NAMING_CEREMONY', 'BABY_SHOWER'],
  },

  // ─── 8. MUNDAN / CHUDAKARANA ────────────────────────────────────────────
  {
    id: 'mundan-sacred-beginnings',
    celebrationType: 'MUNDAN',
    name: 'Sacred Beginnings & Blessings',
    tagline: 'Cream, Saffron, Glowing Diyas & Temple Arches',
    description: 'Devotional Indian Mundan ceremony design with sandalwood tilak, temple bells, brass diyas, and sacred Sanskrit Vedic invocations.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Traditional',
    mood: 'Spiritual',
    texture: 'paper-embossed',
    borderStyle: 'embossed-gold-filigree',
    colorPalette: {
      canvasBg: '#FFFDF7',
      surfaceBg: '#FEF9EE',
      surfaceElevated: '#FDF0D5',
      primary: '#C2410C',
      primaryHover: '#9A3412',
      primaryText: '#FFFFFF',
      accent: '#EAB308',
      accentSoft: 'rgba(234, 179, 8, 0.2)',
      textHeading: '#431407',
      textBody: '#7C2D12',
      textMuted: '#9A3412',
      borderSoft: '#FDE68A',
      borderAccent: '#EAB308',
      gradientHeader: 'linear-gradient(135deg, #C2410C 0%, #EAB308 100%)',
      badgeBg: 'rgba(194, 65, 12, 0.15)',
      badgeText: '#C2410C',
    },
    typography: 'font-serif',
    backgroundStyle: 'sacred-marigold-radial',
    decorationStyle: 'LOTUS_BLOSSOMS',
    animationStyle: 'traditional',
    icon: '🪔',
    badgeIcon: '🪔',
    badgeLabel: 'MUNDAN • SACRED',
    tags: ['TRADITIONAL', 'BABY', 'LIGHT', 'RECOMMENDED'],
    recommendedOccasions: ['MUNDAN', 'CHUDAKARANA', 'TONSURE', 'JADULA'],
    isRecommendedDefault: true,
  },
  {
    id: 'mundan-little-prince',
    celebrationType: 'MUNDAN',
    name: 'Little Prince & Royal Heritage',
    tagline: 'Pastel Blue, Gold Crest & Soft Lighting',
    description: 'Soft baby blue and royal gold trim with traditional Indian peacock motifs and heartfelt blessings for the little one.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'pastel',
    style: 'Royal',
    mood: 'Joyful',
    texture: 'paper-embossed',
    borderStyle: 'palace-arch',
    colorPalette: {
      canvasBg: '#F0F9FF',
      surfaceBg: '#E0F2FE',
      surfaceElevated: '#BAE6FD',
      primary: '#0369A1',
      primaryHover: '#075985',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#0C4A6E',
      textBody: '#075985',
      textMuted: '#0369A1',
      borderSoft: '#7DD3FC',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #0369A1 0%, #F59E0B 100%)',
      badgeBg: 'rgba(3, 105, 161, 0.15)',
      badgeText: '#075985',
    },
    typography: 'font-serif',
    backgroundStyle: 'baby-pastel-radial',
    decorationStyle: 'LOTUS_BLOSSOMS',
    animationStyle: 'traditional',
    icon: '🪷',
    badgeIcon: '🪷',
    badgeLabel: 'MUNDAN • PRINCE',
    tags: ['BABY', 'ROYAL', 'PASTEL'],
    recommendedOccasions: ['MUNDAN', 'FIRST_BIRTHDAY', 'NAAMKARAN'],
  },

  // ─── 9. 1ST BIRTHDAY & MILESTONE BIRTHDAYS ──────────────────────────────
  {
    id: 'birthday-1st-wonderland',
    celebrationType: 'BIRTHDAY',
    name: '1st Birthday Wonderland',
    tagline: 'Pastel Balloons, Stars, Cake & Confetti',
    description: 'Adorable first birthday celebration card featuring colorful floating balloons, sparkling starbursts, tiered birthday cake, and playful joy.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'pastel',
    style: 'Festive',
    mood: 'Playful',
    texture: 'watercolor',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#FEF2F2',
      surfaceBg: '#FEE2E2',
      surfaceElevated: '#FECACA',
      primary: '#E11D48',
      primaryHover: '#BE123C',
      primaryText: '#FFFFFF',
      accent: '#FBBF24',
      accentSoft: 'rgba(251, 191, 36, 0.2)',
      textHeading: '#881337',
      textBody: '#9F1239',
      textMuted: '#BE123C',
      borderSoft: '#FDA4AF',
      borderAccent: '#FBBF24',
      gradientHeader: 'linear-gradient(135deg, #E11D48 0%, #FBBF24 100%)',
      badgeBg: 'rgba(225, 29, 72, 0.15)',
      badgeText: '#E11D48',
    },
    typography: 'font-sans',
    backgroundStyle: 'party-stardust-radial',
    decorationStyle: 'CONFETTI_BALLOONS',
    animationStyle: 'playful',
    icon: '🎂',
    badgeIcon: '🎂',
    badgeLabel: '1ST BIRTHDAY • CUTE',
    tags: ['PASTEL', 'BABY', 'RECOMMENDED'],
    recommendedOccasions: ['FIRST_BIRTHDAY', '1ST_BIRTHDAY', 'KIDS_BIRTHDAY'],
    isRecommendedDefault: true,
  },
  {
    id: 'birthday-celebration-burst',
    celebrationType: 'BIRTHDAY',
    name: 'Celebration Burst & Confetti',
    tagline: 'Golden Confetti, Balloons & Vibrant Lighting',
    description: 'High-energy party atmosphere with floating metallic balloons, exploding golden confetti, and birthday starbursts.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'vibrant',
    style: 'Festive',
    mood: 'Joyful',
    texture: 'metallic',
    borderStyle: 'minimal-dual',
    colorPalette: {
      canvasBg: '#1A0B2E',
      surfaceBg: 'rgba(40, 16, 70, 0.94)',
      surfaceElevated: 'rgba(60, 24, 100, 0.96)',
      primary: '#9333EA',
      primaryHover: '#7E22CE',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#FAF5FF',
      textBody: '#F3E8FF',
      textMuted: '#D8B4FE',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #FAF5FF 0%, #F59E0B 50%, #9333EA 100%)',
      badgeBg: 'rgba(147, 51, 234, 0.3)',
      badgeText: '#D8B4FE',
    },
    typography: 'font-sans',
    backgroundStyle: 'party-stardust-radial',
    decorationStyle: 'CONFETTI_BALLOONS',
    animationStyle: 'festive',
    icon: '🎈',
    badgeIcon: '🎈',
    badgeLabel: 'BIRTHDAY • BURST',
    tags: ['FESTIVE', 'VIBRANT'],
    recommendedOccasions: ['BIRTHDAY', 'TEEN_BIRTHDAY', 'SURPRISE_PARTY'],
  },
  {
    id: 'birthday-milestone-30th',
    celebrationType: 'BIRTHDAY',
    name: '30th Milestone • Black & Gold',
    tagline: 'Matte Black, Metallic Gold Foil & Champagne Lights',
    description: 'Sophisticated adult milestone birthday card with dark luxury matte backdrop, champagne bokeh, and sculpted metallic foil numbers.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Luxury',
    mood: 'Glamorous',
    texture: 'metallic',
    borderStyle: 'metallic-gold-foil',
    colorPalette: {
      canvasBg: '#0A0A0A',
      surfaceBg: 'rgba(24, 24, 27, 0.94)',
      surfaceElevated: 'rgba(39, 39, 42, 0.96)',
      primary: '#CA8A04',
      primaryHover: '#A16207',
      primaryText: '#FFFFFF',
      accent: '#FBBF24',
      accentSoft: 'rgba(251, 191, 36, 0.2)',
      textHeading: '#FAFAFA',
      textBody: '#E4E4E7',
      textMuted: '#A1A1AA',
      borderSoft: 'rgba(251, 191, 36, 0.3)',
      borderAccent: '#FBBF24',
      gradientHeader: 'linear-gradient(135deg, #FAFAFA 0%, #FBBF24 50%, #CA8A04 100%)',
      badgeBg: 'rgba(202, 138, 4, 0.25)',
      badgeText: '#FDE047',
    },
    typography: 'font-sans',
    backgroundStyle: 'platinum-night-radial',
    decorationStyle: 'CONFETTI_BALLOONS',
    animationStyle: 'festive',
    icon: '✨',
    badgeIcon: '✨',
    badgeLabel: '30TH • MILESTONE',
    tags: ['DARK', 'LUXURY'],
    recommendedOccasions: ['MILESTONE_BIRTHDAY', '30TH_BIRTHDAY', '50TH_BIRTHDAY', '60TH_BIRTHDAY'],
  },

  // ─── 10. ANNIVERSARY ────────────────────────────────────────────────────
  {
    id: 'anniversary-forever-us',
    celebrationType: 'ANNIVERSARY',
    name: 'Forever Us & Rose Garden',
    tagline: 'Deep Rose Wine, Golden Candles & Cherished Memories',
    description: 'Emotional anniversary design celebrating love, years of companionship, warm glowing candles, and fragrant rose petals.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Romantic',
    mood: 'Romantic',
    texture: 'velvet',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#15040A',
      surfaceBg: 'rgba(38, 10, 20, 0.94)',
      surfaceElevated: 'rgba(64, 16, 32, 0.96)',
      primary: '#BE185D',
      primaryHover: '#9D174D',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#FDF2F8',
      textBody: '#FCE7F3',
      textMuted: '#F472B6',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #FDF2F8 0%, #F59E0B 50%, #BE185D 100%)',
      badgeBg: 'rgba(190, 24, 93, 0.3)',
      badgeText: '#FBCFE8',
    },
    typography: 'font-serif',
    backgroundStyle: 'romantic-wine-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '💑',
    badgeIcon: '💑',
    badgeLabel: 'ANNIVERSARY • ROMANCE',
    tags: ['ROMANTIC', 'DARK', 'RECOMMENDED'],
    recommendedOccasions: ['ANNIVERSARY', 'WEDDING_ANNIVERSARY', 'SILVER_JUBILEE'],
    isRecommendedDefault: true,
  },

  // ─── 11. RELIGIOUS, PUJA & HOUSEWARMING ──────────────────────────────────
  {
    id: 'housewarming-griha-pravesh',
    celebrationType: 'HOUSEWARMING',
    name: 'Griha Pravesh & Shubh Rangoli',
    tagline: 'Terracotta, Gold, Mango Toran & Sacred Kalash',
    description: 'Auspicious new home blessings card with auspicious Kalash, glowing brass diyas, sacred Swastik, and traditional floral entrance toran.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Traditional',
    mood: 'Spiritual',
    texture: 'paper-embossed',
    borderStyle: 'embossed-gold-filigree',
    colorPalette: {
      canvasBg: '#FFFDF5',
      surfaceBg: '#FEF8E8',
      surfaceElevated: '#FDF0D0',
      primary: '#9A3412',
      primaryHover: '#7C2D12',
      primaryText: '#FFFFFF',
      accent: '#D97706',
      accentSoft: 'rgba(217, 119, 6, 0.15)',
      textHeading: '#431407',
      textBody: '#7C2D12',
      textMuted: '#9A3412',
      borderSoft: '#FDE68A',
      borderAccent: '#D97706',
      gradientHeader: 'linear-gradient(135deg, #9A3412 0%, #D97706 100%)',
      badgeBg: 'rgba(154, 52, 18, 0.15)',
      badgeText: '#9A3412',
    },
    typography: 'font-serif',
    backgroundStyle: 'sacred-marigold-radial',
    decorationStyle: 'FESTIVE_DIYAS',
    animationStyle: 'traditional',
    icon: '🏡',
    badgeIcon: '🏡',
    badgeLabel: 'GRIHA PRAVESH',
    tags: ['TRADITIONAL', 'LIGHT', 'RECOMMENDED'],
    recommendedOccasions: ['GRIHA_PRAVESH', 'HOUSEWARMING', 'HOME_BLESSING'],
    isRecommendedDefault: true,
  },
  {
    id: 'puja-satyanarayan-katha',
    celebrationType: 'FESTIVAL',
    name: 'Satyanarayan Katha & Puja',
    tagline: 'Saffron, Maroon & Sacred Vedic Mandalas',
    description: 'Devotional prayer card with sacred holy fire, brass bell engravings, lotus offerings, and divine Vedic Sanskrit shlokas.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Traditional',
    mood: 'Spiritual',
    texture: 'paper-embossed',
    borderStyle: 'palace-arch',
    colorPalette: {
      canvasBg: '#FFFBEB',
      surfaceBg: '#FEF3C7',
      surfaceElevated: '#FDE68A',
      primary: '#B45309',
      primaryHover: '#92400E',
      primaryText: '#FFFFFF',
      accent: '#EA580C',
      accentSoft: 'rgba(234, 88, 12, 0.15)',
      textHeading: '#78350F',
      textBody: '#92400E',
      textMuted: '#B45309',
      borderSoft: '#FCD34D',
      borderAccent: '#EA580C',
      gradientHeader: 'linear-gradient(135deg, #B45309 0%, #EA580C 100%)',
      badgeBg: 'rgba(180, 83, 9, 0.15)',
      badgeText: '#B45309',
    },
    typography: 'font-serif',
    backgroundStyle: 'sacred-marigold-radial',
    decorationStyle: 'FESTIVE_DIYAS',
    animationStyle: 'traditional',
    icon: '🪷',
    badgeIcon: '🪷',
    badgeLabel: 'PUJA • SACRED',
    tags: ['TRADITIONAL', 'LIGHT'],
    recommendedOccasions: ['PUJA', 'SATYANARAYAN_KATHA', 'HAVAN', 'GANESH_PUJA'],
  },
  {
    id: 'festival-diwali-midnight',
    celebrationType: 'FESTIVAL',
    name: 'Midnight Diwali Splendor',
    tagline: 'Midnight Navy, Glowing Brass Diyas & Golden Rangoli',
    description: 'Festive dark luxury Diwali invitation with glowing clay and brass diyas, radiant golden starlight, and intricate Rangoli patterns.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Festive',
    mood: 'Spiritual',
    texture: 'metallic',
    borderStyle: 'embossed-gold-filigree',
    colorPalette: {
      canvasBg: '#060B19',
      surfaceBg: 'rgba(12, 22, 48, 0.94)',
      surfaceElevated: 'rgba(20, 36, 78, 0.96)',
      primary: '#D97706',
      primaryHover: '#B45309',
      primaryText: '#FFFFFF',
      accent: '#FBBF24',
      accentSoft: 'rgba(251, 191, 36, 0.2)',
      textHeading: '#FEF3C7',
      textBody: '#FDE68A',
      textMuted: '#FCD34D',
      borderSoft: 'rgba(251, 191, 36, 0.3)',
      borderAccent: '#FBBF24',
      gradientHeader: 'linear-gradient(135deg, #FEF3C7 0%, #FBBF24 50%, #D97706 100%)',
      badgeBg: 'rgba(217, 119, 6, 0.3)',
      badgeText: '#FDE68A',
    },
    typography: 'font-serif',
    backgroundStyle: 'sangeet-purple-radial',
    decorationStyle: 'FESTIVE_DIYAS',
    animationStyle: 'traditional',
    icon: '🪔',
    badgeIcon: '🪔',
    badgeLabel: 'DIWALI • MIDNIGHT',
    tags: ['DARK', 'FESTIVE', 'RECOMMENDED'],
    recommendedOccasions: ['DIWALI', 'FESTIVAL', 'DEEPAVALI'],
    isRecommendedDefault: true,
  },

  // ─── 12. CORPORATE & BUSINESS SUMMITS ───────────────────────────────────
  {
    id: 'corporate-business-conference',
    celebrationType: 'CORPORATE',
    name: 'Business Conference & Summit',
    tagline: 'Midnight Navy, Platinum Steel & Minimalist Skyline',
    description: 'Executive corporate card with sleek architectural geometry, platinum reflections, and clean typography tailored for leadership summits.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Modern',
    mood: 'Formal',
    texture: 'silk',
    borderStyle: 'minimal-dual',
    colorPalette: {
      canvasBg: '#0A0F1D',
      surfaceBg: 'rgba(15, 23, 42, 0.94)',
      surfaceElevated: 'rgba(30, 41, 59, 0.96)',
      primary: '#2563EB',
      primaryHover: '#1D4ED8',
      primaryText: '#FFFFFF',
      accent: '#38BDF8',
      accentSoft: 'rgba(56, 189, 248, 0.2)',
      textHeading: '#F8FAFC',
      textBody: '#E2E8F0',
      textMuted: '#94A3B8',
      borderSoft: 'rgba(56, 189, 248, 0.2)',
      borderAccent: '#38BDF8',
      gradientHeader: 'linear-gradient(135deg, #F8FAFC 0%, #38BDF8 50%, #2563EB 100%)',
      badgeBg: 'rgba(37, 99, 235, 0.2)',
      badgeText: '#7DD3FC',
    },
    typography: 'font-sans',
    backgroundStyle: 'corporate-navy-radial',
    decorationStyle: 'GEOMETRIC_TECH_STREAKS',
    animationStyle: 'professional',
    icon: '💼',
    badgeIcon: '💼',
    badgeLabel: 'CORPORATE • SUMMIT',
    tags: ['CORPORATE', 'DARK', 'MODERN', 'RECOMMENDED'],
    recommendedOccasions: ['CORPORATE', 'CONFERENCE', 'BUSINESS_SUMMIT', 'SEMINAR'],
    isRecommendedDefault: true,
  },
  {
    id: 'corporate-annual-awards',
    celebrationType: 'CORPORATE',
    name: 'Annual Awards & Excellence Gala',
    tagline: 'Matte Black, Gold Trophy Beams & Champagne Stage',
    description: 'Prestigious awards night invitation with sweeping golden stage light beams, metallic trophy emblems, and formal executive styling.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Luxury',
    mood: 'Formal',
    texture: 'metallic',
    borderStyle: 'metallic-gold-foil',
    colorPalette: {
      canvasBg: '#09090B',
      surfaceBg: 'rgba(24, 24, 27, 0.94)',
      surfaceElevated: 'rgba(39, 39, 42, 0.96)',
      primary: '#D97706',
      primaryHover: '#B45309',
      primaryText: '#FFFFFF',
      accent: '#FBBF24',
      accentSoft: 'rgba(251, 191, 36, 0.2)',
      textHeading: '#FAFAFA',
      textBody: '#E4E4E7',
      textMuted: '#A1A1AA',
      borderSoft: 'rgba(251, 191, 36, 0.3)',
      borderAccent: '#FBBF24',
      gradientHeader: 'linear-gradient(135deg, #FAFAFA 0%, #FBBF24 50%, #D97706 100%)',
      badgeBg: 'rgba(217, 119, 6, 0.25)',
      badgeText: '#FDE047',
    },
    typography: 'font-serif',
    backgroundStyle: 'platinum-night-radial',
    decorationStyle: 'GEOMETRIC_TECH_STREAKS',
    animationStyle: 'professional',
    icon: '🏆',
    badgeIcon: '🏆',
    badgeLabel: 'AWARDS • GALA',
    tags: ['CORPORATE', 'LUXURY', 'DARK'],
    recommendedOccasions: ['ANNUAL_DAY_AWARDS', 'AWARDS_GALA', 'GALA_DINNER'],
  },

  // ─── 13. GRADUATION / CONVOCATION ───────────────────────────────────────
  {
    id: 'graduation-academic-prestige',
    celebrationType: 'GRADUATION',
    name: 'Academic Prestige & Honors',
    tagline: 'Oxford Navy, Gold Seal, Mortarboard & Ribbon Scroll',
    description: 'Distinguished graduation celebration card with gold foil academic seal, mortarboard cap, parchment scroll, and formal honors styling.',
    previewImage: '/velvet_invitation_chest.jpg',
    thumbnailImage: '/velvet_invitation_chest.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Royal',
    mood: 'Formal',
    texture: 'silk',
    borderStyle: 'minimal-dual',
    colorPalette: {
      canvasBg: '#0B1120',
      surfaceBg: 'rgba(15, 23, 42, 0.94)',
      surfaceElevated: 'rgba(30, 41, 59, 0.96)',
      primary: '#1E40AF',
      primaryHover: '#1E3A8A',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#F8FAFC',
      textBody: '#E2E8F0',
      textMuted: '#94A3B8',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #F8FAFC 0%, #F59E0B 50%, #1E40AF 100%)',
      badgeBg: 'rgba(30, 64, 175, 0.3)',
      badgeText: '#FDE68A',
    },
    typography: 'font-serif',
    backgroundStyle: 'reception-navy-radial',
    decorationStyle: 'GEOMETRIC_TECH_STREAKS',
    animationStyle: 'professional',
    icon: '🎓',
    badgeIcon: '🎓',
    badgeLabel: 'GRADUATION • HONORS',
    tags: ['CORPORATE', 'DARK', 'RECOMMENDED'],
    recommendedOccasions: ['GRADUATION', 'CONVOCATION', 'ACHIEVEMENT'],
    isRecommendedDefault: true,
  },

  // ─── 14. CHARITY & FUNDRAISER ───────────────────────────────────────────
  {
    id: 'charity-humanitarian-gala',
    celebrationType: 'OTHER',
    name: 'Humanitarian Gala & Giving',
    tagline: 'Warm Teal, Coral, Gold & Community Bloom',
    description: 'Heartfelt philanthropic gala invitation with gentle floral wreaths, warm ambient candlelight, and human-centered elegance.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'light',
    style: 'Modern',
    mood: 'Spiritual',
    texture: 'paper-embossed',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#F0FDFA',
      surfaceBg: '#CCFBF1',
      surfaceElevated: '#99F6E4',
      primary: '#0F766E',
      primaryHover: '#115E59',
      primaryText: '#FFFFFF',
      accent: '#F43F5E',
      accentSoft: 'rgba(244, 63, 94, 0.15)',
      textHeading: '#134E4A',
      textBody: '#115E59',
      textMuted: '#0F766E',
      borderSoft: '#5EEAD4',
      borderAccent: '#F43F5E',
      gradientHeader: 'linear-gradient(135deg, #0F766E 0%, #F43F5E 100%)',
      badgeBg: 'rgba(15, 118, 110, 0.15)',
      badgeText: '#0F766E',
    },
    typography: 'font-serif',
    backgroundStyle: 'sage-garden-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '🤝',
    badgeIcon: '🤝',
    badgeLabel: 'CHARITY • GALA',
    tags: ['MODERN', 'LIGHT'],
    recommendedOccasions: ['CHARITY_GALA', 'FUNDRAISER', 'NONPROFIT'],
  },

  // ─── 15. DINNER & COCKTAILS ─────────────────────────────────────────────
  {
    id: 'party-cocktail-night',
    celebrationType: 'OTHER',
    name: 'Cocktails & Candlelight',
    tagline: 'Plum, Black, Gold & Stemmed Crystal Glassware',
    description: 'Intimate evening dinner and cocktail reception with ambient candlelight, wine and cocktail glasses, and dark luxury aesthetic.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Luxury',
    mood: 'Glamorous',
    texture: 'velvet',
    borderStyle: 'minimal-dual',
    colorPalette: {
      canvasBg: '#11030B',
      surfaceBg: 'rgba(32, 8, 20, 0.94)',
      surfaceElevated: 'rgba(54, 12, 34, 0.96)',
      primary: '#9D174D',
      primaryHover: '#831843',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#FDF2F8',
      textBody: '#FCE7F3',
      textMuted: '#F472B6',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #FDF2F8 0%, #F59E0B 50%, #9D174D 100%)',
      badgeBg: 'rgba(157, 23, 77, 0.3)',
      badgeText: '#FBCFE8',
    },
    typography: 'font-serif',
    backgroundStyle: 'romantic-wine-radial',
    decorationStyle: 'ROSE_PETALS_HEARTS',
    animationStyle: 'romantic',
    icon: '🍸',
    badgeIcon: '🍸',
    badgeLabel: 'COCKTAIL • NIGHT',
    tags: ['DARK', 'GLAMOROUS'],
    recommendedOccasions: ['COCKTAIL_PARTY', 'DINNER_PARTY', 'BACHELOR_PARTY'],
  },

  // ─── 16. UNIVERSAL MODERN CELEBRATION ───────────────────────────────────
  {
    id: 'celebration-universal-modern',
    celebrationType: 'OTHER',
    name: 'Modern Universal Celebration',
    tagline: 'Abstract Radiant Bokeh & Golden Ambient Lights',
    description: 'An elegant, versatile design with glowing ambient bokeh, modern serif typography, and balanced celebratory aesthetics for any gathering.',
    previewImage: '/romantic_3d_invitation_hero.jpg',
    thumbnailImage: '/romantic_3d_invitation_hero.jpg',
    imageSource: 'LOCAL',
    mode: 'luxury-dark',
    style: 'Modern',
    mood: 'Elegant',
    texture: 'silk',
    borderStyle: 'ornate-scalloped',
    colorPalette: {
      canvasBg: '#0F0308',
      surfaceBg: 'rgba(26, 6, 14, 0.94)',
      surfaceElevated: 'rgba(56, 11, 27, 0.96)',
      primary: '#7E223B',
      primaryHover: '#63182C',
      primaryText: '#FFFFFF',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.2)',
      textHeading: '#FFF8E7',
      textBody: '#EAD7BD',
      textMuted: '#C2A383',
      borderSoft: 'rgba(245, 158, 11, 0.3)',
      borderAccent: '#F59E0B',
      gradientHeader: 'linear-gradient(135deg, #FFF8E7 0%, #F59E0B 50%, #7E223B 100%)',
      badgeBg: 'rgba(126, 34, 59, 0.3)',
      badgeText: '#FDE68A',
    },
    typography: 'font-serif',
    backgroundStyle: 'romantic-wine-radial',
    decorationStyle: 'GOLD_SPARKLES_EMERALD',
    animationStyle: 'romantic',
    icon: '✨',
    badgeIcon: '✨',
    badgeLabel: 'UNIVERSAL • MODERN',
    tags: ['MODERN', 'ROYAL', 'RECOMMENDED'],
    recommendedOccasions: ['OTHER', 'REUNION', 'FAMILY_REUNION', 'CELEBRATION'],
    isRecommendedDefault: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// HELPER FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────
export const getFilteredCelebrationThemes = (
  filterTag: string = 'ALL',
  celebrationType?: string,
  modeFilter: string = 'ALL',
  styleFilter: string = 'ALL'
): CelebrationTheme[] => {
  let themes = [...MASTER_THEME_CATALOG];
  const cType = (celebrationType || '').toUpperCase().trim();

  // 1. If filtering by occasion priority
  if (cType && filterTag === 'RECOMMENDED') {
    return themes.filter(
      (t) =>
        t.recommendedOccasions.includes(cType) ||
        t.celebrationType === cType ||
        t.tags.includes('RECOMMENDED')
    );
  }

  // 2. Tag / Category filter
  if (filterTag !== 'ALL') {
    const fTag = filterTag.toUpperCase();
    themes = themes.filter((t) => {
      if (fTag === 'LIGHT') return t.mode === 'light' || t.mode === 'pastel';
      if (fTag === 'DARK') return t.mode === 'dark' || t.mode === 'luxury-dark';
      if (fTag === 'PASTEL') return t.mode === 'pastel';
      if (fTag === 'VIBRANT') return t.mode === 'vibrant';
      return (
        t.tags.includes(fTag) ||
        t.style.toUpperCase() === fTag ||
        t.mood.toUpperCase() === fTag
      );
    });
  }

  // 3. Mode filter
  if (modeFilter !== 'ALL') {
    themes = themes.filter((t) => t.mode === modeFilter);
  }

  // 4. Style filter
  if (styleFilter !== 'ALL') {
    themes = themes.filter((t) => t.style === styleFilter);
  }

  // 5. If specific celebration type provided and no specific tag filter, prioritize matching themes first
  if (cType && filterTag === 'ALL') {
    themes.sort((a, b) => {
      const aMatch = a.recommendedOccasions.includes(cType) || a.celebrationType === cType;
      const bMatch = b.recommendedOccasions.includes(cType) || b.celebrationType === cType;
      if (aMatch && !bMatch) return -1;
      if (!aMatch && bMatch) return 1;
      return 0;
    });
  }

  return themes;
};

export const getCelebrationThemeById = (themeId?: string): CelebrationTheme => {
  if (!themeId) return MASTER_THEME_CATALOG[0];

  // Direct match
  const found = MASTER_THEME_CATALOG.find((t) => t.id === themeId);
  if (found) return found;

  // Partial match for backward compatibility
  const partial = MASTER_THEME_CATALOG.find(
    (t) => t.id.includes(themeId) || themeId.includes(t.id)
  );
  if (partial) return partial;

  return MASTER_THEME_CATALOG[0];
};

export const getRecommendedThemeForOccasion = (occasionId: string): CelebrationTheme => {
  const occ = (occasionId || '').toUpperCase().trim();
  const match = MASTER_THEME_CATALOG.find(
    (t) =>
      (t.recommendedOccasions.includes(occ) || t.celebrationType === occ) &&
      t.isRecommendedDefault
  );
  if (match) return match;

  const fallbackMatch = MASTER_THEME_CATALOG.find(
    (t) => t.recommendedOccasions.includes(occ) || t.celebrationType === occ
  );
  if (fallbackMatch) return fallbackMatch;

  return MASTER_THEME_CATALOG[0];
};
